// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUA8KPMeeL3Tclv5izcQK00xn1ADvok2A',
    appId: '1:683757721292:web:b418f6ac34c899e6bf1469',
    messagingSenderId: '683757721292',
    projectId: 'lawyerbano-e4644',
    authDomain: 'lawyerbano-e4644.firebaseapp.com',
    storageBucket: 'lawyerbano-e4644.firebasestorage.app',
    measurementId: 'G-96EFV6VPX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6SClkzCpFzB2YSCxSmP_j8K4YwMblLHo',
    appId: '1:683757721292:android:37885216df5220f5bf1469',
    messagingSenderId: '683757721292',
    projectId: 'lawyerbano-e4644',
    storageBucket: 'lawyerbano-e4644.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYQoUBns2DwcepGYtd36sXJo5qQlPh9To',
    appId: '1:683757721292:ios:f5df4429376980e0bf1469',
    messagingSenderId: '683757721292',
    projectId: 'lawyerbano-e4644',
    storageBucket: 'lawyerbano-e4644.firebasestorage.app',
    iosBundleId: 'com.example.lawyerbanoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYQoUBns2DwcepGYtd36sXJo5qQlPh9To',
    appId: '1:683757721292:ios:f5df4429376980e0bf1469',
    messagingSenderId: '683757721292',
    projectId: 'lawyerbano-e4644',
    storageBucket: 'lawyerbano-e4644.firebasestorage.app',
    iosBundleId: 'com.example.lawyerbanoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUA8KPMeeL3Tclv5izcQK00xn1ADvok2A',
    appId: '1:683757721292:web:8d61e1253dba4db9bf1469',
    messagingSenderId: '683757721292',
    projectId: 'lawyerbano-e4644',
    authDomain: 'lawyerbano-e4644.firebaseapp.com',
    storageBucket: 'lawyerbano-e4644.firebasestorage.app',
    measurementId: 'G-QBYRDCH9V6',
  );
}
